/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.IObjekat;
import domen.Radnik;
import domen.StavkaRacuna;
import javax.swing.JOptionPane;
import logika.Kontroler;
import modeli.ModelTabeleStavki;
import niti.NitSat;

/**
 *
 * @author Maja
 */
public class GlavnaForma extends javax.swing.JFrame {

    IObjekat radnik;
    
    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        NitSat ns = new NitSat(lblSat);
        ns.start();
    }

    public void setRadnik(IObjekat radnik) {
        this.radnik = radnik;
        Radnik r = (Radnik) radnik;
        labelaUlogovaniRadnik.setText("Ulogovani radnik je: "+r.getIme()+" "+r.getPrezime());
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelaUlogovaniRadnik = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSat = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiUnosProizvoda = new javax.swing.JMenuItem();
        jmiPretragaProizvoda = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiUnosRacuna = new javax.swing.JMenuItem();
        jmiPretragaBris = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelaUlogovaniRadnik.setText("jLabel1");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/kafic.png"))); // NOI18N

        lblSat.setText("jLabel2");

        jMenu1.setText("Rad sa proizvodima");

        jmiUnosProizvoda.setText("Unos proizvoda");
        jmiUnosProizvoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosProizvodaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiUnosProizvoda);

        jmiPretragaProizvoda.setText("Izmena, brisanje i pretraga");
        jmiPretragaProizvoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaProizvodaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiPretragaProizvoda);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Rad sa racunima");

        jmiUnosRacuna.setText("Unos racuna");
        jmiUnosRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosRacunaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiUnosRacuna);

        jmiPretragaBris.setText("Pretraga i brisanje");
        jmiPretragaBris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaBrisActionPerformed(evt);
            }
        });
        jMenu2.add(jmiPretragaBris);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelaUlogovaniRadnik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSat)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelaUlogovaniRadnik)
                    .addComponent(lblSat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        String porukaSaServera = Kontroler.getInstanca().zavrsiSaRadom();
        JOptionPane.showMessageDialog(this, porukaSaServera, "Hvala od srca", JOptionPane.INFORMATION_MESSAGE);
    }  
    private void jmiUnosProizvodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosProizvodaActionPerformed
        UnosProizvodaForma upf = new UnosProizvodaForma(this, true);
        upf.pack();
        upf.setVisible(true);
    }//GEN-LAST:event_jmiUnosProizvodaActionPerformed

    private void jmiPretragaProizvodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaProizvodaActionPerformed
        ManipulacijaProizvodima mp = new ManipulacijaProizvodima();
        mp.setVisible(true);
        this.setVisible(false);
        mp.setGlavna(this);
    }//GEN-LAST:event_jmiPretragaProizvodaActionPerformed

    private void jmiUnosRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosRacunaActionPerformed
        UnosRacunaForma urf = new UnosRacunaForma(radnik, this);
        urf.srediZaUnos();
        urf.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jmiUnosRacunaActionPerformed

    private void jmiPretragaBrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaBrisActionPerformed
        ManipulacijaRacunima mr = new ManipulacijaRacunima();
        mr.setVisible(true);
        this.setVisible(false);
        mr.setGlavna(this);
    }//GEN-LAST:event_jmiPretragaBrisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiPretragaBris;
    private javax.swing.JMenuItem jmiPretragaProizvoda;
    private javax.swing.JMenuItem jmiUnosProizvoda;
    private javax.swing.JMenuItem jmiUnosRacuna;
    private javax.swing.JLabel labelaUlogovaniRadnik;
    private javax.swing.JLabel lblSat;
    // End of variables declaration//GEN-END:variables

   

    
}
