/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.IObjekat;
import domen.Proizvod;
import domen.Racun;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import konstante.Konstante;
import logika.Kontroler;
import modeli.ModelTabeleProizvoda;
import modeli.ModelTabeleRacuna;
import povezivanje.Komunikacija;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Maja
 */
public class ManipulacijaRacunima extends javax.swing.JFrame {
    
    GlavnaForma gf ;

    /**
     * Creates new form ManipulacijaRacunima
     */
    public ManipulacijaRacunima() {
        initComponents();
        tblRacuni.setModel(new ModelTabeleRacuna());
        prikaziRacune();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRacuni = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        btnDetalji = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnVratiMe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prikaz racuna");

        tblRacuni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRacuni);

        jLabel1.setText("Pretraga po datumu:");

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnDetalji.setText("Detalji");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnVratiMe.setText("Vrati me na meni");
        btnVratiMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVratiMeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVratiMe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDetalji, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btnVratiMe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVratiMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVratiMeActionPerformed
        gf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVratiMeActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        int red = tblRacuni.getSelectedRow();
        ModelTabeleRacuna mtr = (ModelTabeleRacuna) tblRacuni.getModel();
        
        if(red != -1){
            Racun r = mtr.dajRacun(red);
            UnosRacunaForma urf = new UnosRacunaForma(null, gf);
            urf.setForma(this);
            urf.srediFormuZaDetalje(r);
            urf.setVisible(true);
            this.setVisible(false); 
        }

    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        srediTabelu();
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int red = tblRacuni.getSelectedRow();
        ModelTabeleRacuna mtr = (ModelTabeleRacuna) tblRacuni.getModel();
        Racun r = mtr.dajRacun(red);
        int response = JOptionPane.showConfirmDialog(this, "Da li sigurno zelite da obrisete izabrani racun?", "Brisanje racuna", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.OK_OPTION) {
            ServerskiOdgovor so = Kontroler.getInstanca().obrisiRacun(r);
            
            if (so.isUspesno()) {
                JOptionPane.showMessageDialog(this, so.getPoruka(), "Uspesno", JOptionPane.INFORMATION_MESSAGE);
                prikaziRacune();
            } 
            else {
                JOptionPane.showMessageDialog(this, so.getPoruka(), "Neuspesno", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManipulacijaRacunima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManipulacijaRacunima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManipulacijaRacunima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManipulacijaRacunima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManipulacijaRacunima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnVratiMe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRacuni;
    private javax.swing.JTextField txtDatum;
    // End of variables declaration//GEN-END:variables

    void setGlavna(GlavnaForma aThis) {
        this.gf = aThis;
    }

    private void srediTabelu() {
        String dat = txtDatum.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        try {
            Date datum = sdf.parse(dat);
            Racun r = new Racun();
            r.setDatumIzrade(datum);
            
            ServerskiOdgovor so = Kontroler.getInstanca().pretraziRacune(r);

            if(so.isUspesno()){
                List<IObjekat> listaRacuna = (List<IObjekat>) so.getOdgovor();
                if(listaRacuna.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Sistem nije pronasao racune po zadatim kriterijumima pretrage");
                    return;
                }
                ModelTabeleRacuna mtr = new ModelTabeleRacuna();
                mtr.setLista(listaRacuna);
                tblRacuni.setModel(mtr);
                JOptionPane.showMessageDialog(this, "Sistem je pronasao racune po zadatim kriterijumima pretrage");
            }
            else{
            JOptionPane.showMessageDialog(this, "Sistem nije pronasao racune po zadatim kriterijumima pretrage");
            }        
            
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Datum nije u dobrom formatu","Greska", JOptionPane.ERROR_MESSAGE);
        }    
    }

    private void prikaziRacune() {
            Racun r = new Racun();
            r.setDatumIzrade(null);
            
            ServerskiOdgovor so = Kontroler.getInstanca().pretraziRacune(r);

            if(so.isUspesno()){
                List<IObjekat> listaRacuna = (List<IObjekat>) so.getOdgovor();
                if(listaRacuna.isEmpty()){
                    return;
                }
                ModelTabeleRacuna mtr = new ModelTabeleRacuna();
                mtr.setLista(listaRacuna);
                tblRacuni.setModel(mtr);
            }
            else{
            JOptionPane.showMessageDialog(this, "Sistem nije pronasao racune");
            }        
            
           
    }

    
}
